# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import SuperStream_pb2 as SuperStream__pb2


class SuperStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAnswer = channel.stream_stream(
                '/SuperStream/getAnswer',
                request_serializer=SuperStream__pb2.ClientMessage.SerializeToString,
                response_deserializer=SuperStream__pb2.ServerReply.FromString,
                )


class SuperStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAnswer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAnswer': grpc.stream_stream_rpc_method_handler(
                    servicer.getAnswer,
                    request_deserializer=SuperStream__pb2.ClientMessage.FromString,
                    response_serializer=SuperStream__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SuperStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuperStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAnswer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SuperStream/getAnswer',
            SuperStream__pb2.ClientMessage.SerializeToString,
            SuperStream__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
